bavix/laravel-wallet

database/migrations/2018_11_07_192923_create_transfers_table.php
@rez1dent3 requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/bavix/laravel-wallet/
=> Scrutinizer Auto-Fixes

changelog.md, composer.json, database/migrations_v1/2018_11_06_222923_create_transactions_table.php, database/migrations_v2/2018_11_19_164609_update_transactions_table.php
=> add support mariadb 10.1

src/Commands/RefreshBalance.php, tests/BalanceTest.php
=> Refresh command

.phpstorm.meta.php, composer.json, config/config.php, src/Interfaces/Storable.php, src/Services/CommonService.php, src/Services/ProxyService.php, src/Services/WalletService.php, src/Simple/MemoryStore.php, src/Simple/Store.php, src/Traits/HasWallet.php, src/WalletServiceProvider.php, tests/BalanceTest.php, tests/TestCase.php
=> #103 add storable

docs/basic-usage.md, docs/cart.md, docs/gift.md, docs/pay-free.md, docs/payment.md, docs/refund.md, docs/ru/basic-usage.md, docs/ru/cart.md, docs/ru/gift.md, docs/ru/pay-free.md, docs/ru/payment.md, docs/ru/refund.md, docs/ru/taxing.md, docs/taxing.md, src/Interfaces/Product.php, src/Objects/Cart.php, src/Traits/CartPay.php, src/Traits/HasGift.php, tests/CartTest.php, tests/DiscountTest.php, tests/GiftTest.php, tests/MinTaxTest.php, tests/Models/Item.php, tests/MultiWalletGiftTest.php, tests/MultiWalletTest.php, tests/ProductTest.php, tests/TaxTest.php
=> Add the ability to calculate the price relative to the wallet

.travis.yml, docker-compose.yml
=> add percona 8 & mariadb 10

changelog.md, database/migrations_v2/2019_05_13_111553_update_status_transfers_table.php, database/migrations_v2/2019_06_25_103755_add_exchange_status_transfers_table.php, src/Services/CommonService.php, tests/BalanceTest.php
=> 5.x fix bug

changelog.md, src/Services/CommonService.php, tests/BalanceTest.php, tests/CartTest.php
=> 6.x bug fix

resources/lang/ar/errors.php
=> add arabic locale

src/Objects/Cart.php, src/Services/MetaService.php, src/Traits/CartPay.php, src/WalletServiceProvider.php, tests/CartTest.php, tests/Factories/ItemMetaFactory.php, tests/Models/ItemMeta.php
=> Added transfer of meta-information through the cart

database/2018_11_15_124230_create_wallets_table.php
=> migrate:refresh fix

composer.json, config/config.php, depfile.yaml, docs/_sidebar.md, docs/balance-updated-event.md, docs/event-customize.md, src/Internal/Assembler/BalanceUpdatedEventAssembler.php, src/Internal/Assembler/BalanceUpdatedEventAssemblerInterface.php, src/Internal/Events/BalanceUpdatedEvent.php, src/Internal/Events/BalanceUpdatedEventInterface.php, src/Internal/Events/EventInterface.php, src/Internal/Exceptions/ExceptionInterface.php, src/Internal/Exceptions/UnknownEventException.php, src/Internal/Service/ClockService.php, src/Internal/Service/ClockServiceInterface.php, src/Internal/Service/DispatcherService.php, src/Internal/Service/DispatcherServiceInterface.php, src/Models/Wallet.php, src/Services/RegulatorService.php, src/WalletServiceProvider.php, tests/Infra/Listeners/BalanceUpdatedThrowDateListener.php, tests/Infra/Listeners/BalanceUpdatedThrowIdListener.php, tests/Infra/Listeners/BalanceUpdatedThrowUuidListener.php, tests/Infra/Services/ClockFakeService.php, tests/Units/Domain/EventTest.php, tests/Units/Service/DispatcherTest.php
As part of this pull request, only one event will be added:
- BalanceUpdatedEvent
=> [7.2] Events

src/Models/Wallet.php, src/Services/ConsistencyService.php, src/Services/ConsistencyServiceInterface.php, src/Traits/HasWallet.php, src/Traits/HasWalletFloat.php, tests/Units/Domain/CreditWalletTest.php
- Adding credit limits;
- Optimization of check for withdrawals;
=> [7.x] Credit Limits

changelog.md, composer.json, src/Internal/Service/DispatcherService.php
=> Event dispatcher to interface

composer.json
https://infection.github.io/2021/07/27/whats-new-in-0.24.0/#Major-performance-improvement-for-the-projects-with-slow-test-suites-using-only-covering-test-cases-option
=> Major performance improvement for the projects with slow test suites, using --only-covering-test-cases option

src/Internal/Dto/BasketDto.php, src/Internal/Dto/ItemDto.php, src/Internal/Dto/ItemDtoInterface.php, src/Objects/Cart.php, src/Services/BasketService.php, src/Services/PurchaseService.php, src/Traits/CartPay.php, tests/Units/Domain/BasketTest.php, tests/Units/Domain/ProductTest.php
Until I made a decision on the fate of this pull request. The issue needs to be studied.
=> [9.x] Product custom price

tests/Units/Domain/BlockTest.php, tests/Units/Domain/CreditWalletTest.php
- https://github.com/bavix/laravel-wallet/issues/174
- https://github.com/bavix/laravel-wallet/issues/416
=> Examples of solving problems that arise for users.

docs/basic-usage.md, docs/cart.md, docs/gift.md, docs/pay-free.md, docs/payment.md, docs/refund.md
@nathanwritescode-uk thank you. #511
=> Typos in interfaces and copy-paste

src/Internal/Service/LockService.php, src/WalletServiceProvider.php
=> Change CacheManager to CacheFactory for compatibility with Lumen

changelog.md, config/config.php, docs/_sidebar.md, docs/transaction-created-event.md, src/Internal/Assembler/TransactionCreatedEventAssembler.php, src/Internal/Assembler/TransactionCreatedEventAssemblerInterface.php, src/Internal/Events/TransactionCreatedEvent.php, src/Internal/Events/TransactionCreatedEventInterface.php, src/Internal/Service/DispatcherService.php, src/Services/TransactionService.php, src/WalletServiceProvider.php, tests/Infra/Listeners/TransactionCreatedThrowListener.php, tests/Units/Domain/EventTest.php
=> [9.1] TransactionCreatedEvent

deptrac.yaml, docs/transaction.md, src/Internal/Decorator/StorageServiceLockDecorator.php, src/Internal/Service/LockService.php, src/Internal/Service/StorageService.php, src/Internal/Service/StorageServiceInterface.php, src/Services/AtomicService.php, src/Services/BookkeeperService.php, src/Services/RegulatorService.php, src/WalletServiceProvider.php, tests/Units/Service/StorageTest.php
https://github.com/bavix/laravel-wallet/discussions/565
=> [9.3] StorageServiceLockDecorator

config/config.php, src/Internal/Decorator/StorageServiceLockDecorator.php, src/Internal/Service/LockService.php, src/Internal/Service/LockServiceInterface.php, src/Internal/Service/StateService.php, src/Internal/Service/StateServiceInterface.php, src/Models/Wallet.php, src/Services/AtomicService.php, src/Traits/CanConfirm.php, src/Traits/CanExchange.php, src/Traits/HasWallet.php, src/WalletServiceProvider.php
https://github.com/bavix/laravel-wallet/discussions/562
=> [9.3] StateServiceInterface 

src/Internal/Service/DispatcherService.php, src/Internal/Service/DispatcherServiceInterface.php, src/Services/WalletService.php
=> [9.x] Fixed WalletService::create() without db::transaction()

tests/Units/Domain/EventTest.php
=> [9.x] Adding a wallet creation event check for a muti wallet

src/External/Api/TransactionQueryHandlerInterface.php, src/External/Api/TransferQueryHandlerInterface.php, src/Services/AssistantServiceInterface.php, src/Services/AtmServiceInterface.php, src/Services/AtomicServiceInterface.php, src/Services/BasketServiceInterface.php, src/Services/BookkeeperServiceInterface.php, src/Services/CastServiceInterface.php, src/Services/ConsistencyServiceInterface.php, src/Services/DiscountServiceInterface.php, src/Services/EagerLoaderServiceInterface.php, src/Services/ExchangeServiceInterface.php, src/Services/PrepareServiceInterface.php, src/Services/PurchaseServiceInterface.php, src/Services/RegulatorServiceInterface.php, src/Services/TaxServiceInterface.php, src/Services/TransactionServiceInterface.php, src/Services/TransferServiceInterface.php, src/Services/WalletServiceInterface.php, src/Traits/HasWallet.php, tests/Infra/Listeners/BalanceUpdatedThrowIdListener.php, tests/Infra/Listeners/BalanceUpdatedThrowUuidListener.php, tests/Infra/Listeners/TransactionCreatedThrowListener.php, tests/Units/Domain/BalanceTest.php, tests/Units/Domain/EagerLoadingTest.php, tests/Units/Domain/EventTest.php, tests/Units/Domain/MultiWalletTest.php, tests/Units/Domain/StateTest.php, tests/Units/Domain/WalletTest.php
There are problems with laravel nova. Described in #658
=> [10.x] Do not create a wallet when receiving a balance

phpstan-baseline.neon, src/External/Contracts/ExtraDtoInterface.php, src/External/Contracts/OptionDtoInterface.php, src/External/Dto/Extra.php, src/External/Dto/Option.php, src/Internal/Assembler/ExtraDtoAssembler.php, src/Internal/Assembler/TransactionDtoAssembler.php, src/Internal/Assembler/TransactionDtoAssemblerInterface.php, src/Internal/Assembler/TransferDtoAssembler.php, src/Internal/Assembler/TransferDtoAssemblerInterface.php, src/Internal/Assembler/TransferLazyDtoAssembler.php, src/Internal/Assembler/TransferLazyDtoAssemblerInterface.php, src/Internal/Dto/TransferLazyDto.php, src/Internal/Dto/TransferLazyDtoInterface.php, src/Services/PrepareService.php, src/Services/PrepareServiceInterface.php, src/Services/TransferService.php, src/Traits/CanExchange.php, src/Traits/HasGift.php
This pull request is a logical continuation of https://github.com/bavix/laravel-wallet/pull/552.
=> [10.x] Asynchronous wallet operations. v2

src/Internal/Service/StateService.php
… working directly with StateService.
=> [10.x] Fixed possible bug when working directly with StateService

phpstan.tests.neon, phpunit.xml, src/Internal/Service/LockService.php, src/Services/EagerLoaderService.php, src/Services/TransactionService.php, src/Services/TransferService.php, tests/Infra/Exceptions/PriceNotSetException.php, tests/Infra/Factories/ItemMultiPriceFactory.php, tests/Infra/Models/ItemMultiPrice.php, tests/Units/Domain/MultiWalletTest.php, tests/migrations/2018_11_08_214421_create_items_table.php
Recently, a question is often asked about multi-price for a product. Here is an example.
=> [10.x] Example. Multiple prices for a product

docs/lumen.md
=> Lumen documentation update

docs/configuration.md
documented how to override wallet decimal_places
=> docs: changing wallet decimal_places

composer.json, rector.php
The project is half-dead and constantly breaking down
=> remove driftingly/rector-laravel

tests/Units/Domain/DiscountTest.php
=> add a check for passing the correct model

src/Models/Wallet.php, tests/Units/Service/AtomicServiceTest.php
Add received transfers function for v10
=> [10.x] received transfers

tests/Units/Domain/ExtraTest.php
=> Pending Balances 

tests/Units/Domain/CreditWalletTest.php
=> Frozen balance

config/config.php, database/2021_11_02_202021_update_wallets_uuid_table.php, docs/guide/cqrs/create-wallet.md, src/Internal/Assembler/TransactionDtoAssembler.php, src/Internal/Assembler/TransferDtoAssembler.php, src/Internal/Service/IdentifierFactoryService.php, src/Internal/Service/IdentifierFactoryServiceInterface.php, src/Internal/Service/UuidFactoryService.php, src/Internal/Service/UuidFactoryServiceInterface.php, src/Models/Wallet.php, src/Services/WalletService.php, src/WalletServiceProvider.php, tests/Units/Domain/BlockTest.php, tests/Units/Domain/EventTest.php, tests/Units/Domain/ExtraTest.php, tests/Units/Domain/MultiWalletTest.php, tests/Units/Service/WalletTest.php
Why do you need it? To get more performance in MySQL databases
=> [11.3] UUID7. IdentifierFactoryServiceInterface

README.md, composer.json, database/2018_11_06_222923_create_transactions_table.php, database/2018_11_07_192923_create_transfers_table.php, database/2018_11_15_124230_create_wallets_table.php, phpstan.common.neon, phpstan.src.baseline.neon, phpstan.tests.baseline.neon, rector.php, tests/Infra/TestCase.php
#1024
WARNING. PR has problems with mysql/mariadb prefix.
https://github.com/laravel/framework/issues/54817
=> [11.x] Laravel 12
