bavix/laravel-wallet

src/Services/WalletService.php
@rez1dent3 requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/bavix/laravel-wallet/
=> Scrutinizer Auto-Fixes

src/Wallet.php, src/WalletServiceProvider.php
Borrowing from Laravel's official packages, this allows default migrations to be ignored.
Calling the Wallet::ignoreMigrations method in the register method of your AppServiceProvider will prevent the default migrations from being run.
As noted [in the documentation](https://bavix.github.io/laravel-wallet/#/installation?id=run-migrations), the default migrations can be published with the `php artisan vendor:publish --tag=laravel-wallet-migrations` command.
Example:
```
use Bavix\Wallet\Wallet;
class AppServiceProvider extends ServiceProvider
{
/**
* Register any application services.
*
* @return void
*/
public function register()
{
Wallet::ignoreMigrations();
}
```
=> Allow default migrations to be ignored

database/migrations_v2/2019_05_13_111553_update_status_transfers_table.php, database/migrations_v2/2019_06_25_103755_add_exchange_status_transfers_table.php
Faced issue while executing migrations. Identified that in some migrations, DB::statement is being used and when DB Table Prefix is configured in the config/database.php file, it is not building the correct table names in those statements.
For the fix, the `DB::getTablePrefix()` is appended to all the places where the table name is being used as a direct statement.
Kindly accept PR or share feedback for corrections if required.
=> Fixed migration issue with db table prefix

src/Interfaces/Wallet.php, src/Models/Wallet.php, src/Traits/HasWallet.php, tests/Units/Domain/MultiWalletTest.php
#416 
```php
// default wallet
$user->deposit(100);
$user->wallet->deposit(200);
$user->wallet->withdraw(1);
// usd
$usd = $user->createWallet(['name' => 'USD']);
$usd->deposit(100);
// eur
$eur = $user->createWallet(['name' => 'EUR']);
$eur->deposit(100);
$user->transactions()->count(); // 5
$user->wallet->transactions()->count(); // 5
$usd->transactions()->count(); // 5
$eur->transactions()->count(); // 5
// the transactions method returns data relative to the owner of the wallet, for all transactions
$user->walletTransactions()->count(); // 3. we get the default wallet
$user->wallet->walletTransactions()->count(); // 3
$usd->walletTransactions()->count(); // 1
$eur->walletTransactions()->count(); // 1
```
=> Add a relation for fetching transactions from the wallet (walletTransactions)

src/Internal/Dto/TransactionDto.php, src/Internal/Dto/TransactionDtoInterface.php, src/Internal/Dto/TransferDto.php, src/Internal/Dto/TransferDtoInterface.php
This PR extends wallet holder_id property to support string type.
In my use case, user id and item id are uuid strings.
=> Extend Wallet holder_id property to support string type

changelog.md, docs/_sidebar.md, docs/nova-action.md, docs/transaction.md, src/Internal/Exceptions/ExceptionInterface.php, src/Internal/Exceptions/TransactionStartException.php, src/Internal/Service/DatabaseService.php, src/Internal/Service/DatabaseServiceInterface.php, tests/Units/Domain/TransactionsFilterTest.php, tests/Units/Service/DatabaseTest.php
=> Checking the transaction level at startup

src/Interfaces/Customer.php, src/Interfaces/Product.php, src/Interfaces/ProductInterface.php, src/Interfaces/ProductLimitedInterface.php, src/Internal/Dto/BasketDto.php, src/Internal/Dto/BasketDtoInterface.php, src/Internal/Dto/ItemDto.php, src/Internal/Dto/ItemDtoInterface.php, src/Objects/Cart.php, src/Services/BasketService.php, src/Services/MetaServiceLegacy.php, src/Traits/CanPay.php, src/Traits/CartPay.php, src/Traits/HasGift.php, tests/Infra/Models/Item.php
I have seen a lot of projects implemented on this package and most use the shopping functionality for endless products. There was a need to split the product interface into two (limited product and unlimited product). Usually, unlimited is understood as the internal currency of the site, services and other rapidly renewable goods.
=> [9.x] Split Product interface

README.md
The interface names are the wrong way around; a limited number of products should implement `ProductLimitedInterface`, whilst an unlimited number of products should implement `ProductInterface`.
=> Replacing the README interface names with the correct ones

src/Traits/HasWallet.php
This PR is attempt to fix https://github.com/bavix/laravel-wallet/issues/516, as on post https://github.com/bavix/laravel-wallet/issues/516#issuecomment-1157715295 pointed out, it already provide the arg to not execute save.
so we can leverage that, if user id is not present, we set the method `getWallet` argument `$save` as false.
this will ensure, when authenticated user id will auto save, 
when execute without any authentication for this instance, laravel-ide-helper would not execute save
```bash
➜  laravel-wallet git:(master) ✗ phpunit --stop-on-failure
PHPUnit 9.5.20 #StandWithUkraine
Runtime:       PHP 8.0.8
Configuration: /Users/keatliang/Downloads/laravel-wallet/phpunit.xml
Warning:       No code coverage driver available …
```
=> Fix laravel-ide-helper generate:model

src/Models/Transaction.php, tests/Units/Domain/TransactionAmountFloatAccessorTest.php
=> Fix transaction amount_float mutator 

src/Services/WalletService.php, tests/Units/Service/WalletTest.php
With a large number of wallets, you want to insert into the database asynchronously (in a queue).
It becomes possible to generate a unique key in advance and give it to the frontend.
```php
$user->createWallet([
'uuid' => $uuid,
'name' => 'my wallet',
]);
```
=> [9.2] Ability to dynamically create a wallet

src/Internal/Service/LockService.php, src/Services/AssistantServiceInterface.php, src/Services/AtmServiceInterface.php, src/Services/AtomicService.php, src/Services/AtomicServiceInterface.php, src/Services/BasketServiceInterface.php, src/Services/EagerLoaderServiceInterface.php, src/Services/ExchangeServiceInterface.php, src/Traits/CanExchange.php, tests/Units/Domain/CartTest.php, tests/Units/Domain/WalletFloatTest.php, tests/Units/Service/AtomicServiceTest.php, tests/Units/Service/LockServiceTest.php, tests/Units/Service/SingletonTest.php
Extend the interface for multiple atomic operations on multiple wallets.
```php
/**
* Use when you need to atomically change a lot of wallets and atomic in its pure form is not suitable. Use with
* caution, generates N requests to the lock service.
*
* @param non-empty-array<Wallet> $objects
*
* @throws LockProviderNotFoundException
* @throws RecordsNotFoundException
* @throws TransactionFailedException
* @throws ExceptionInterface
*/
public function blocks(array $objects, callable $callback): mixed;
```
The main message is to be able to change the balance of several wallets atomically.
```php
$this->atomicService->blocks(
[$user1->wallet, $user2->wallet],
fn () => collect([
fn () => $user1->transfer($user2, 500),
fn () => $user1->transfer($user2, 500),
fn () => $user2->transfer($user1, …
```
=> [9.2] Allow to use atomic service

src/Models/Transaction.php, src/Models/Transfer.php, src/Models/Wallet.php, tests/Units/Domain/SilentlyDiscardingTest.php
=> [9.4] add support Model::preventSilentlyDiscardingAttributes()

composer.json, phpstan-baseline.neon, src/Internal/Service/DatabaseService.php, src/Internal/Service/LockService.php, src/Internal/Service/StateService.php, src/Internal/Service/StorageService.php, src/Services/RegulatorService.php, src/WalletServiceProvider.php, tests/Units/Service/StorageTest.php
WARNING: Never use package services in a constructor!!!
#570
=> [9.4] partial octane support

config/config.php, phpstan-baseline.neon, psalm-baseline.xml, psalm.xml, src/Internal/Decorator/StorageServiceLockDecorator.php, src/Internal/Exceptions/RecordNotFoundException.php, src/Internal/Repository/WalletRepository.php, src/Internal/Service/LockService.php, src/Internal/Service/LockServiceInterface.php, src/Internal/Service/StateService.php, src/Internal/Service/StateServiceInterface.php, src/Internal/Service/StorageService.php, src/Internal/Service/StorageServiceInterface.php, src/Services/AtomicService.php, src/Services/BookkeeperService.php, src/Services/BookkeeperServiceInterface.php, src/Services/RegulatorService.php, src/WalletServiceProvider.php, tests/Units/Service/BookkeeperTest.php, tests/Units/Service/LockServiceTest.php, tests/Units/Service/StorageTest.php
- Redis. All requests inside the AtomicService will be executed in a transaction;
- Memcached. Requests will be combined into multiGet and multiSet. Performance boost;
---
Without config key `cache.ttl` package saves the cache forever.
For users who pushed the wallet.php configuration into their project, the application logic will remain unchanged, and for new projects ttl will be added to the default configuration.
If ttl is set to null, then you will get a "forever" cache situation. The cache lives by default for 24 hours.
```php
'cache' => [
'driver' => '...',
'ttl' => 24 * 3600,
],
```
What problem should TTL solve? Then the "cold" data will no longer take up space in RAM.
=> [9.5] Cache query optimize. v2

.github/workflows/phpunits.yaml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Deprecating save-state and set-output commands

src/Models/Transfer.php, src/Services/PurchaseService.php, tests/Units/Upgrade/TransferFixTest.php
Starting from version 9.0, the package wrote the value "Wallet" in the from/to type header and used it in queries, which reduced performance. In the current PR, I want to get away from unnecessary data. The columns themselves will be removed in version 11.x
=> [10.x] Remove the use of the _type field in queries. Performance

composer.json, ecs.php, src/Models/Transaction.php, src/Models/Transfer.php, src/Models/Wallet.php, src/Objects/Cart.php, src/Traits/CanPay.php, src/Traits/CartPay.php, src/Traits/HasGift.php, src/Traits/HasWallet.php, src/Traits/HasWallets.php, src/WalletServiceProvider.php, tests/Units/Api/TransactionHandlerTest.php, tests/Units/Api/TransferHandlerTest.php, tests/Units/Domain/BalanceTest.php, tests/Units/Domain/CartReceivingTest.php, tests/Units/Domain/CartTest.php, tests/Units/Domain/MultiWalletTest.php, tests/Units/Domain/StateTest.php
=> Update symplify/easy-coding-standard requirement from ^11.5 to ^12.0

docs/configuration.md
Move package configuration to a separate section
=> docs: Create configuration.md

changelog.md, src/Traits/MorphOneWallet.php, tests/Infra/Factories/UserDynamicFactory.php, tests/Infra/Models/UserDynamic.php, tests/Units/Domain/WalletTest.php
=> [10.x] add getDynamicDefaultSlug

src/Models/Transfer.php
Update Transfer model to support dynamic loading of overwritten Wallet or Transaction model classes. 
Defaults to current Wallet and Transaction model from inside the package if no overwritten models specified.
=> Update Transfer Model

database/2024_01_24_185401_add_extra_column_in_transfer.php, phpstan.src.baseline.neon, src/External/Contracts/ExtraDtoInterface.php, src/External/Dto/Extra.php, src/Internal/Assembler/TransferDtoAssembler.php, src/Internal/Assembler/TransferDtoAssemblerInterface.php, src/Internal/Assembler/TransferLazyDtoAssembler.php, src/Internal/Assembler/TransferLazyDtoAssemblerInterface.php, src/Internal/Dto/BasketDto.php, src/Internal/Dto/BasketDtoInterface.php, src/Internal/Dto/TransferDto.php, src/Internal/Dto/TransferDtoInterface.php, src/Internal/Dto/TransferLazyDto.php, src/Internal/Dto/TransferLazyDtoInterface.php, src/Internal/Repository/TransferRepository.php, src/Internal/Transform/TransferDtoTransformer.php, src/Internal/Transform/TransferDtoTransformerInterface.php, src/Models/Transfer.php, src/Objects/Cart.php, src/Services/PrepareService.php, src/Services/TransferService.php, src/Traits/CanExchange.php, src/Traits/HasGift.php, tests/Units/Api/TransferHandlerTest.php, tests/Units/Domain/BasketTest.php, tests/Units/Domain/CartTest.php, tests/Units/Domain/ExtraTest.php
#864
Example 1:
```php
$transfers = $transferQueryHandler->apply([
new TransferQuery(
$from,
$to,
100,
new Extra(
null,
null,
'598c184c-e6d6-4fc2-9640-c1c7acb38093',
['type' => 'first'],
),
),
]);
```
Example 2:
```php
$transfer = $user1->transfer(
$user2,
500,
new Extra(
deposit: [
'type' => 'extra-deposit',
],
withdraw: new Option(
[
'type' => 'extra-withdraw',
],
false
),
extra: ['msg' => 'hello world'],
)
);
```
=> [11.x] Adding an Extra column to the transfer table 

deptrac.yaml, src/External/Api/TransactionFloatQuery.php, src/External/Api/TransferFloatQuery.php, tests/Units/Api/TransactionHandlerTest.php, tests/Units/Api/TransferHandlerTest.php
#857
Added a convenient contract for package users `TransferFloatQuery`.
```php
app(TransferQueryHandlerInterface::class)->apply([
new TransferFloatQuery($from, $to, .93, null),
]);
```
=> [11.x] Added *FloatQuery for High performance api handles

src/Interfaces/Wallet.php, src/Models/Wallet.php, src/Traits/HasWallet.php, tests/Units/Service/AtomicServiceTest.php
Adds the functionality of received transfers relationship to v11
=> [11.x] received transfers

.github/workflows/phpunits.yaml, tests/Infra/TestCase.php
https://github.com/laravel/framework/pull/48455
```
Changes default collation for MySQL to utf8mb4_0900_ai_ci
Changes default collation for MariaDB to utf8mb4_uca1400_ai_ci
```
=> [11.x] revert collation

src/Internal/Observers/TransactionObserver.php, src/Internal/Observers/TransferObserver.php, src/Traits/CanConfirm.php, tests/Units/Domain/ConfirmTest.php, tests/Units/Domain/SoftDeletesTest.php
=> allow deletion of unconfirmed operations without forceDelete

phpstan.src.baseline.neon, src/Traits/CanConfirm.php, tests/Units/Domain/ConfirmTest.php, tests/Units/Domain/EagerLoadingTest.php
Within the transaction, make an additional query to the database to check the transaction confirmation.
=> [11.2] Improvements to confirm

database/2021_11_02_202021_update_wallets_uuid_table.php
This PR will fix the drop issue on migration rollback by removing the column `uuid` as index before it drop the column.
=> [11.x] Fix UUID Drop on migration rollback

tests/Infra/TestCase.php
This reverts commit 19bd0915cd73b288431a1fafa53b0d30091c0a01.
=> Revert "remove prefix for mysql/mariadb"
